FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster-run-20190717

RUN apt-get update && apt-get install -yq --no-install-recommends \
  rsync \
  openssh-client \
  e2fsprogs \
  samba \
  cifs-utils \
  cryptsetup \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*


COPY smb_data_share.conf /tmp/
RUN cat /tmp/smb_data_share.conf >> /etc/samba/smb.conf

# Start app
ADD start.sh /start.sh
CMD ["bash", "/start.sh"]