FROM balenalib/%%BALENA_MACHINE_NAME%%-node:latest-buster-run

RUN apt-get update && apt-get install -yq --no-install-recommends \
  rsync \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# Start app
CMD tail -f /dev/null