FROM balenalib/%%BALENA_MACHINE_NAME%%-node:latest-buster-run

RUN apt-get update && apt-get install -yq --no-install-recommends \
  rsync \
  openssh-client \
  e2fsprogs \
  samba \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/*


COPY smb_data_share.conf /tmp/
RUN cat /tmp/smb_data_share.conf >> /etc/samba/smb.conf

# Start app
CMD tail -f /dev/null